---
- hosts: all
  vars:
    carvel_apps:
      - name: ytt
        version: 0.45.0
      - name: kbld
        version: 0.36.4
      - name: imgpkg
        version: 0.36.0
      - name: kapp
        version: 0.55.0
      - name: vendir
        version: 0.33.1
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - loop: '{{ carvel_apps | default([]) }}'
      loop_control:
        loop_var: carvel_app
      include_tasks: test-app.yml
