---
- hosts: all
  vars:
    carvel_apps:
      - name: ytt
        version: 0.50.0
      - name: kbld
        version: 0.38.1
      - name: imgpkg
        version: 0.39.0
      - name: kapp
        version: 0.63.2
      - name: vendir
        version: 0.38.0
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Testing app installs
      loop: '{{ carvel_apps | default([]) }}'
      loop_control:
        loop_var: carvel_app
      ansible.builtin.include_tasks: test-app.yml
