---
- hosts: all
  vars:
    carvel_apps:
      - name: ytt
        version: 0.40.1
      - name: kbld
        version: 0.33.0
      - name: imgpkg
        version: 0.28.0
      - name: kapp
        version: 0.47.0
      - name: vendir
        version: 0.26.0
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - loop: '{{ carvel_apps | default([]) }}'
      loop_control:
        loop_var: carvel_app
      include_tasks: test-app.yml
