---
- name: Resolving vars for {{ carvel_app.name }}:{{ carvel_app.version }}
  ansible.builtin.include_vars:
    file: app-install-vars.yml
- name: Downloading {{ carvel_app_url }} to {{ carvel_app_exe }}
  become: '{{ carvel_elevate }}'
  become_user: root
  ansible.builtin.get_url:
    url: '{{ carvel_app_url }}'
    dest: '{{ carvel_app_exe }}'
    mode: '755'
    checksum: sha256:{{ carvel_app_checksums_url }}
- name: Linking {{ carvel_app_link }} to {{ carvel_app_exe }}
  become: '{{ carvel_elevate }}'
  become_user: root
  ansible.builtin.file:
    state: link
    src: '{{ carvel_app_exe }}'
    dest: '{{ carvel_app_link }}'
